### ISSUE TITLE
Help in retrieving the attributes of a node

### ISSUE THREAD

**Issue by poojagaonkar** [iabudiab/HTMLKit#3]
Hello,

First of all, a very nice library you have created here. I am using it for a feature in my app where I need to load a HTML string , select node with particular tags and fetch the attributes of name and value from those tags. I have reached this far :

```
HTMLParser *parser = [[HTMLParser alloc]initWithString : htmlString];
HTMLElement *htmlElement = [[HTMLElement alloc] initWithTagName:@"//input[@type = 'hidden']"];
NSArray *nodes = [parser parseFragmentWithContextElement : htmlElement];

for(HTMLNode *node in nodes)
{
   // Here I want to have the attributes of the node 
  // e.g. something like node.Attributes["name"].Value and  node.Attributes["value"].Value

}
```

It would be great if you could help me out and guide me in the right direction as I am quite new to iOS.
Thank you.

**Comment by iabudiab** [comment]
@poojagaonkar Hey, I see that you've closed the issue already. Do you still need help with your problem? Will be glad to help 😉

**Comment by poojagaonkar** [comment]
Hey,

Thanks for replying. I couldn't solve the issue, but could continue without
using the feature for the time being.

It would be nice if you could still help me solve it if I need to implement
it in future.

Thanks again :)

Pooja

**Comment by iabudiab** [comment]
Hey, no problem. First things first, I'm not really sure what you are trying to accomplish and why you are using the fragment parsing, so here is my interpretation:

    // First you parse the htmlString into a document
    HTMLDocument *doc = [HTMLDocument documentWithString:htmlString];
    // Then you qeury the document for all input elements that are hidden
    NSArray *hiddenInputs = [doc querySelectorAll:@"input[type=hidden]"];
    
    // Now you iterate the elements array
    for (HTMLElement *element in hiddenInputs) {
        NSLog(@"%@: %@", element.attributes[@"name"], element.attributes[@"value"]);
    }

You couldn't access the `attributes` in your case because you were iterating an array of `HTMLNode`s. A HTMLNode can be any type of DOM node, e.g. a text node or comment node, but only `HTMLElement`s have attributes.

So in your case you have to check the node's type and cast accordingly. something like this:

    for (HTMLNode *node in nodes) {
        if (node.nodeType != HTMLNodeElement) {
            continue;
        }
        HTMLElement *element = (HTMLElement *)node;
        // You logic here
    }

Let me know if this answers your questions.
